apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-sample
    app.kubernetes.io/part-of: m4-demo-5
  name: nodejs-sample
  namespace: alexeykazakov
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: nodejs-sample
status:
  loadBalancer: {}
